/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogistica.administrativo;


import aplicacionlogistica.configuracion.CambiarClave;
import aplicacionlogistica.configuracion.Inicio;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarDocumentosEmpleados;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarEmpleados;
import aplicacionlogistica.distribucion.formularios.reportes.rptDocumentosEmpleados;
import aplicacionlogistica.distribucion.objetos.personas.CUsuarios;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VLI_488
 */
public class PrincipalTalentoHumanoAuxiliar extends javax.swing.JFrame {

    Inicio ini=null;
    CUsuarios user;
   
    public void setUser(CUsuarios user) {
        this.user = user;
    }

    public CUsuarios getUser() {
        return user;
    }

    
    
    public PrincipalTalentoHumanoAuxiliar() {
        initComponents();
        
    }
   
    public PrincipalTalentoHumanoAuxiliar(Inicio ini) throws Exception {
        
         this.ini = ini;
        user = ini.getUser();
        ini = new Inicio(user.getNombreUsuario());
        if (ini.isClienteActivo()) {
            initComponents();this.setSize(ini.getDimension());
            this.setLocation(0,0);
            this.setTitle("Sistema de Información Logistica    -- Usuario de Sistema: " + user.getNombres() + " " + user.getApellidos() );
           // CUsuarios user= new CUsuarios(ini.getUsuarioDelSistema(), ini.getCedulaUsuarioDelSistema());
            if(user.getClaveUsuario().equals(Inicio.cifrar("123456"))){ // cuando el usuario es nuevo
                this.escritorio.setSize(600, 400);
                 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                 CambiarClave form= new CambiarClave(this);
                 form.txtUsuario.setText(Inicio.deCifrar(user.getNombreUsuario()));
                 form.txtClaveAnterior.requestFocus();
                 PrincipalTalentoHumanoAuxiliar.escritorio.add(form);
                 form.setSize(escritorio.getSize());
                 form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
                 jMenuBar1.setVisible(true);
                 form.show();
                 
           }else{
                this.escritorio.setSize(600, 400);
                 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                 CambiarClave form= new CambiarClave(ini);
                 PrincipalTalentoHumanoAuxiliar.escritorio.add(form);
                 form.setSize(escritorio.getSize());
                 form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
                 jMenuBar1.setVisible(true);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Estimado usuario la licencia ha caducado, consulte con el administrador", "Cliente no activo", 1);
            System.exit( 0 ); 
        }
            
       
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuCambiarClave = new javax.swing.JMenuItem();
        jMenuLogistica = new javax.swing.JMenu();
        mnuCrearEmpleados = new javax.swing.JMenuItem();
        mnuAsignarDocumentos = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        menuRptDocumentosEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        escritorio.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        jMenuBar1.setEnabled(false);

        menuArchivo.setText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        menuCambiarClave.setText("Cambio de Clave");
        menuCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCambiarClaveActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCambiarClave);

        jMenuBar1.add(menuArchivo);

        jMenuLogistica.setText("Talento Humano");

        mnuCrearEmpleados.setText("Crear Empleados");
        mnuCrearEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearEmpleadosActionPerformed(evt);
            }
        });
        jMenuLogistica.add(mnuCrearEmpleados);

        mnuAsignarDocumentos.setText("Asignar documentos");
        mnuAsignarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsignarDocumentosActionPerformed(evt);
            }
        });
        jMenuLogistica.add(mnuAsignarDocumentos);

        jMenuBar1.add(jMenuLogistica);

        jMenuReportes.setText("Reportes");

        menuRptDocumentosEmpleados.setText("Reporte Documentos Empleados");
        menuRptDocumentosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRptDocumentosEmpleadosActionPerformed(evt);
            }
        });
        jMenuReportes.add(menuRptDocumentosEmpleados);

        jMenuBar1.add(jMenuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
       
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void menuCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCambiarClaveActionPerformed
        try {
            this.escritorio.setSize(600, 400);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            CambiarClave form= new CambiarClave(ini);
            form.txtUsuario.setText(Inicio.deCifrar(user.getNombreUsuario()));
            form.txtClaveAnterior.requestFocus();
            PrincipalTalentoHumanoAuxiliar.escritorio.add(form);
            form.setSize(escritorio.getSize());
            form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
            form.show();
        } catch (Exception ex) {
            Logger.getLogger(PrincipalTalentoHumanoAuxiliar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCambiarClaveActionPerformed

    private void menuRptDocumentosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRptDocumentosEmpleadosActionPerformed
              rptDocumentosEmpleados form;
              form = new rptDocumentosEmpleados(this.ini);
              PrincipalTalentoHumanoAuxiliar.escritorio.add(form);
              form.setSize(escritorio.getSize());
              form.show();   
    }//GEN-LAST:event_menuRptDocumentosEmpleadosActionPerformed

    private void mnuAsignarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsignarDocumentosActionPerformed
            
              IngresarDocumentosEmpleados form1= new IngresarDocumentosEmpleados(ini);
              PrincipalTalentoHumanoAuxiliar.escritorio.add(form1);
              form1.setSize(escritorio.getSize());
              form1.show();
    }//GEN-LAST:event_mnuAsignarDocumentosActionPerformed

    private void mnuCrearEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearEmpleadosActionPerformed
       IngresarEmpleados form= new IngresarEmpleados(ini);
       PrincipalTalentoHumanoAuxiliar.escritorio.add(form);
       form.setSize(escritorio.getSize());
       form.show();
    }//GEN-LAST:event_mnuCrearEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTalentoHumanoAuxiliar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new PrincipalTalentoHumanoAuxiliar().setVisible(true);
                
            }
        });
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("aplicacionlogistica/imagenes/turbo_64x64.png"));


        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuLogistica;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuCambiarClave;
    private javax.swing.JMenuItem menuRptDocumentosEmpleados;
    private javax.swing.JMenuItem mnuAsignarDocumentos;
    private javax.swing.JMenuItem mnuCrearEmpleados;
    // End of variables declaration//GEN-END:variables
}
