/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogistica.administrativo;
import aplicacionlogistica.distribucion.formularios.FManifestarPedidosEnRuta;
import aplicacionlogistica.configuracion.CambiarClave;
import aplicacionlogistica.distribucion.*;
import aplicacionlogistica.distribucion.importarExcel.FImportarArchivoExcel;
import aplicacionlogistica.distribucion.Threads.HiloAuxConsultaEmpleados;
import aplicacionlogistica.configuracion.Inicio;
import aplicacionlogistica.distribucion.administracion.TalentoHUmano.FCrearCargos;
import aplicacionlogistica.distribucion.formularios.administracion.FCrearDocumentos;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarCarros;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarDocumentosEmpleados;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarEmpleados;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarUsuarios;
import aplicacionlogistica.distribucion.formularios.reportes.ReporteEmpleados;
import aplicacionlogistica.distribucion.objetos.personas.CEmpleados;
import aplicacionlogistica.distribucion.objetos.personas.CUsuarios;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VLI_488
 */
public class PrincipalAdministrador extends javax.swing.JFrame {

    Inicio ini = null;
    CUsuarios user;
    ArrayList<CEmpleados> arrEmpleados=null;

    public void setUser(CUsuarios user) {
        this.user = user;
    }

    public CUsuarios getUser() {
        return user;
    }

    public PrincipalAdministrador() {
        initComponents();

    }

    public ArrayList<CEmpleados> getArrEmpleados() {
        return arrEmpleados;
    }
    

    public PrincipalAdministrador(Inicio ini) throws Exception, Throwable {

        //initComponents();
        this.ini = ini;
        this.user=ini.getUser();
        
        
        if (ini.isEstaClienteActivo()) {
            initComponents();
            this.setLocation(0, 0);
            this.setTitle("Sistema de Información Logistica    -- Usuario de Sistema: " + user.getNombres() + " " + user.getApellidos());
            //CUsuarios user= new CUsuarios(ini.getUsuarioDelSistema(), ini.getCedulaUsuarioDelSistema());
            
            /* si el cliente es nuevo, entonces en la primera iteracion debe cambiar la clave para
            que pueda trabjar la aplicacoón. la clave inicial es 123456.
            */
            if (user.getClaveUsuario().equals(Inicio.cifrar("123456"))) { // cuando el usuario es nuevo
                
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                CambiarClave form = new CambiarClave(this);
                this.escritorio.setSize(screenSize);
                form.txtUsuario.setText(Inicio.deCifrar(user.getNombreUsuario()));
                form.txtClaveAnterior.requestFocus();
                this.escritorio.add(form);
                form.setLocation((screenSize.width - form.getSize().width) / 2, (screenSize.height - form.getSize().height) / 2);
                jMenuBar1.setVisible(false);
                form.show();

            } else {
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                this.escritorio.setSize(screenSize);
                CambiarClave form = new CambiarClave(ini);
                PrincipalAdministrador.escritorio.add(form);
                form.setLocation((screenSize.width - form.getSize().width) / 2, (screenSize.height - form.getSize().height) / 2);
                jMenuBar1.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Estimado usuario la licencia ha caducado, consulte con el administrador", "Cliente no activo", 1);
            System.exit(0); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuCambiarClave = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        menuIngresarEmpleados = new javax.swing.JMenuItem();
        menuIngresarUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenuLogistica = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAsignarDocumentos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuCrearCentrosDeCosto = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        mnuCrearDocumentos = new javax.swing.JMenuItem();
        jMenu35 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        mnuIngresarCarros = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        mnuDocumentos = new javax.swing.JMenu();
        mnuCarros = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        escritorio.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        jMenuBar1.setEnabled(false);

        menuArchivo.setText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        menuCambiarClave.setText("Cambio de Clave");
        menuCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCambiarClaveActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCambiarClave);

        jMenuItem18.setText("Salir");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        menuArchivo.add(jMenuItem18);

        jMenuBar1.add(menuArchivo);

        jMenuAdministracion.setText("Organizacion");

        menuIngresarEmpleados.setText("Agencias");
        menuIngresarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIngresarEmpleadosMouseClicked(evt);
            }
        });
        menuIngresarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarEmpleadosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(menuIngresarEmpleados);

        menuIngresarUsuarios.setText("Barrios");
        menuIngresarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarUsuariosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(menuIngresarUsuarios);

        jMenu3.setText("Vehiculos");
        jMenuAdministracion.add(jMenu3);

        jMenu6.setText("Ciudades");
        jMenuAdministracion.add(jMenu6);

        jMenu8.setText("Departamentos");
        jMenuAdministracion.add(jMenu8);

        jMenu18.setText("Paises");
        jMenuAdministracion.add(jMenu18);

        jMenu20.setText("Regionales");
        jMenuAdministracion.add(jMenu20);

        jMenu34.setText("Zonas");
        jMenuAdministracion.add(jMenu34);

        jMenuBar1.add(jMenuAdministracion);

        jMenuLogistica.setText("Talento Humano");

        jMenu2.setText("Cargos");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuAsignarDocumentos.setText("Crear Cargos");
        menuAsignarDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAsignarDocumentosMouseClicked(evt);
            }
        });
        menuAsignarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignarDocumentosActionPerformed(evt);
            }
        });
        jMenu2.add(menuAsignarDocumentos);

        jMenuItem1.setText("Asignar Documentos Por Cargo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuLogistica.add(jMenu2);

        jMenu5.setText("Proyectos");

        mnuCrearCentrosDeCosto.setText("Crae Centros de Costo");
        jMenu5.add(mnuCrearCentrosDeCosto);

        jMenuLogistica.add(jMenu5);

        jMenu10.setText("Departamentos");

        jMenuItem2.setText("Crear Departamentos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem2);

        jMenuItem3.setText("Asignar Documentos Por Departamento");
        jMenu10.add(jMenuItem3);

        jMenuItem10.setText("CrearTipos Departamentos");
        jMenu10.add(jMenuItem10);

        jMenuLogistica.add(jMenu10);

        jMenu11.setText("Empleados");

        jMenuItem4.setText("Crer Empleados");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem4);

        jMenuItem5.setText("Documentos por empleado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem5);

        jMenuLogistica.add(jMenu11);

        jMenu12.setText("Entidades Bancarias");

        jMenuItem6.setText("Crear Bancos");
        jMenu12.add(jMenuItem6);

        jMenuLogistica.add(jMenu12);

        jMenu13.setText("Estados Civiles");

        jMenuItem7.setText("Crear Estados Civiles");
        jMenu13.add(jMenuItem7);

        jMenuLogistica.add(jMenu13);

        jMenu17.setText("Usuarios");

        jMenuItem8.setText("Crear Nivelse de Acceso");
        jMenu17.add(jMenuItem8);

        jMenuItem9.setText("Crear Tipos de Acceso");
        jMenu17.add(jMenuItem9);

        jMenuItem13.setText(" Crear Usuarios");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem13);

        jMenuLogistica.add(jMenu17);

        jMenu21.setText("CrearRoles por persona");
        jMenuLogistica.add(jMenu21);

        jMenu24.setText("Crear ");
        jMenuLogistica.add(jMenu24);

        jMenu26.setText("CrearTipos de Sangre");
        jMenuLogistica.add(jMenu26);

        jMenu30.setText("Crear Tipos de Roles");
        jMenuLogistica.add(jMenu30);

        mnuCrearDocumentos.setText("Crear Documentos");
        mnuCrearDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearDocumentosActionPerformed(evt);
            }
        });
        jMenuLogistica.add(mnuCrearDocumentos);

        jMenu35.setText("Reportes Talento Humano");

        jMenuItem14.setText("Listado de  Empleados");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu35.add(jMenuItem14);

        jMenuLogistica.add(jMenu35);

        jMenuBar1.add(jMenuLogistica);

        mnuIngresarCarros.setText("Vehiculos");
        mnuIngresarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresarCarrosActionPerformed(evt);
            }
        });

        jMenu4.setText("Tracto Camiones");

        jMenuItem11.setText("Cabezotes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Trailers");
        jMenu4.add(jMenuItem12);

        mnuIngresarCarros.add(jMenu4);

        mnuDocumentos.setText("Documentos de Transporte");
        mnuIngresarCarros.add(mnuDocumentos);

        mnuCarros.setText("Carros");
        mnuCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCarrosActionPerformed(evt);
            }
        });

        jMenuItem15.setText("Ingresar Carros");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mnuCarros.add(jMenuItem15);

        mnuIngresarCarros.add(mnuCarros);

        jMenu15.setText("Lineas vehiculos");
        mnuIngresarCarros.add(jMenu15);

        jMenu16.setText("Marcas Vehiculos");
        mnuIngresarCarros.add(jMenu16);

        jMenu23.setText("Tipos Carrocerias");
        mnuIngresarCarros.add(jMenu23);

        jMenu25.setText("Tipos Contratos");
        mnuIngresarCarros.add(jMenu25);

        jMenu27.setText("Tipos de Servicio");
        mnuIngresarCarros.add(jMenu27);

        jMenu28.setText("Tipos de Sistemas");
        mnuIngresarCarros.add(jMenu28);

        jMenu29.setText("Tipos Documentos");
        mnuIngresarCarros.add(jMenu29);

        jMenu31.setText("Tipos de sub Sistemas");
        mnuIngresarCarros.add(jMenu31);

        jMenu32.setText("Tipos de Vehiculos");
        mnuIngresarCarros.add(jMenu32);

        jMenu9.setText("Importar Excel");

        jMenuItem16.setText("Importar Excel facturas");
        jMenuItem16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem16MouseClicked(evt);
            }
        });
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem16);

        mnuIngresarCarros.add(jMenu9);

        jMenu14.setText("distribucion");

        jMenuItem17.setText("manifiestos");
        jMenuItem17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem17MouseClicked(evt);
            }
        });
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem17);

        mnuIngresarCarros.add(jMenu14);

        jMenuBar1.add(mnuIngresarCarros);

        jMenu1.setText("Clientes");

        jMenu7.setText("Clientes");
        jMenu1.add(jMenu7);

        jMenu19.setText("Productos");
        jMenu1.add(jMenu19);

        jMenu22.setText("Rutero");
        jMenu1.add(jMenu22);

        jMenu33.setText("Rutas");
        jMenu1.add(jMenu33);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIngresarEmpleadosMouseClicked
    }//GEN-LAST:event_menuIngresarEmpleadosMouseClicked

    private void menuIngresarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarEmpleadosActionPerformed
      
    }//GEN-LAST:event_menuIngresarEmpleadosActionPerformed

    private void menuAsignarDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignarDocumentosMouseClicked
        switch (user.getTipoAcceso()) {
            case 1: // no tiene acceso

                break;
            case 2: // acceso total
                switch (user.getNivelAcceso()) {
                    case 1:

                        break;
                    case 2:

                        break;
                    case 3:

                        break;
                    case 4:

                        break;

                }
                break;
            case 3: // acceso a nivel Administrativo
                switch (user.getNivelAcceso()) {
                    case 1:

                        break;
                    case 2:

                        break;
                    case 3:

                        break;
                    case 4:

                        break;

                }
            case 4: // Acceso a nivel de seguridad
                switch (user.getNivelAcceso()) {
                    case 1:

                        break;
                    case 2:

                        break;
                    case 3:

                        break;
                    case 4:

                        break;

                }
            case 5: // Acceso a nivel de Operativo
                switch (user.getNivelAcceso()) {
                    case 1:

                        break;
                    case 2:

                        break;
                    case 3:

                        break;
                    case 4:

                        break;

                }
            default:
        }
    }//GEN-LAST:event_menuAsignarDocumentosMouseClicked

    private void menuAsignarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignarDocumentosActionPerformed
        switch (user.getTipoAcceso()) {
            case 0:
                break;
            case 1:

                break;
            case 2:
                    FCrearCargos form1 = new FCrearCargos(ini);
                    PrincipalAdministrador.escritorio.add(form1);
                    form1.show();  
        
                break;
            case 3:
                    FCrearCargos form2 = new FCrearCargos(ini);
                    PrincipalTalentoHumanoAdministrador.escritorio.add(form2);
                    form2.show();  
                break;
            case 4:
                    FCrearCargos form3 = new FCrearCargos(ini);
                    PrincipalTalentoHumanoAuxiliar.escritorio.add(form3);
                    form3.show();
                break;
            default:
                break;
        }

    }//GEN-LAST:event_menuAsignarDocumentosActionPerformed

    private void menuIngresarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarUsuariosActionPerformed
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        switch (ini.getTipoDeacceso()) {
            case 0:
                break;
            case 1:
                IngresarUsuarios form;
                try {
              form = new IngresarUsuarios(ini);
              
              this.escritorio.add(form);
             form.setLocation((screenSize.width - form.getSize().width) / 2, (screenSize.height - form.getSize().height) / 2);
              form.show();       
                } catch (Exception ex) {
                    Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                }

                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            default:
                break;
        }

    }//GEN-LAST:event_menuIngresarUsuariosActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void menuCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCambiarClaveActionPerformed
        try {
           
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            CambiarClave form = new CambiarClave(ini);
             this.escritorio.setSize(screenSize);
            PrincipalAdministrador.escritorio.add(form);
            
            form.setLocation((screenSize.width - form.getSize().width) / 2, (screenSize.height - form.getSize().height) / 2);
            form.show();
        } catch (Exception ex) {
            Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCambiarClaveActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        IngresarDocumentosEmpleados form1 = new IngresarDocumentosEmpleados(ini);
        PrincipalAdministrador.escritorio.add(form1);
        form1.setSize(escritorio.getSize());
        form1.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        IngresarEmpleados form2 = new IngresarEmpleados(ini);
        PrincipalAdministrador.escritorio.add(form2);
        //form2.setSize(escritorio.getSize());
        form2.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        //IngresarUsuarios form2;
        try {
            IngresarUsuarios form2 = new IngresarUsuarios(ini);
            PrincipalAdministrador.escritorio.add(form2);
            //form2.setSize(escritorio.getSize());
            form2.show();
        } catch (Exception ex) {
            Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
              IngresarDocumentosEmpleados form1= new IngresarDocumentosEmpleados(ini);
              PrincipalAdministrador.escritorio.add(form1);
              //form1.setSize(escritorio.getSize());
              form1.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnuCrearDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearDocumentosActionPerformed
    
        switch (user.getTipoAcceso()) {
            case 0:
                break;
            case 1:

                break;
            case 2:
                    FCrearDocumentos form1 = new FCrearDocumentos(this.ini);
                    PrincipalAdministrador.escritorio.add(form1);
                    form1.show();  
        
                break;
            case 3:
                    FCrearDocumentos form2 = new FCrearDocumentos(this.ini);
                    PrincipalTalentoHumanoAdministrador.escritorio.add(form2);
                    form2.show();  
                break;
            case 4:
                    FCrearDocumentos form3 = new FCrearDocumentos(this.ini);
                    PrincipalTalentoHumanoAuxiliar.escritorio.add(form3);
                    form3.show();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_mnuCrearDocumentosActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
       ReporteEmpleados form1;
        switch (user.getTipoAcceso()) {
            case 0:
                break;
            case 1:

                break;
            case 2:
                     form1 = new ReporteEmpleados(ini);
                    PrincipalAdministrador.escritorio.add(form1);
                     //form1.setSize(escritorio.getSize());
                   if(arrEmpleados==null){
            try {  
                new Thread(new HiloAuxConsultaEmpleados(ini,5,form1)).start();
            } catch (Exception ex) {
                Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }
                    form1.show();  
        
                break;
            case 3:
                     form1 = new ReporteEmpleados(ini);
                    PrincipalTalentoHumanoAdministrador.escritorio.add(form1);
                     //form1.setSize(escritorio.getSize());
                    if(arrEmpleados==null){
            try {  
                new Thread(new HiloAuxConsultaEmpleados(ini,5,form1)).start();
            } catch (Exception ex) {
                Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }
                    form1.show();  
                break;
            case 4:
                     form1 = new ReporteEmpleados(ini);
                    PrincipalTalentoHumanoAuxiliar.escritorio.add(form1);
                     //form1.setSize(escritorio.getSize());
                    if(arrEmpleados==null){
            try {  
                new Thread(new HiloAuxConsultaEmpleados(ini,5,form1)).start();
            } catch (Exception ex) {
                Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
            }
                    }
                   
                    form1.show();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void mnuIngresarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresarCarrosActionPerformed
     
    }//GEN-LAST:event_mnuIngresarCarrosActionPerformed

    private void mnuCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCarrosActionPerformed
    
    }//GEN-LAST:event_mnuCarrosActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
       IngresarCarros form1 = new IngresarCarros(ini);
     PrincipalAdministrador.escritorio.add(form1);
     form1.show(); 
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem16MouseClicked
     
    }//GEN-LAST:event_jMenuItem16MouseClicked

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
     FImportarArchivoExcel form1 = new FImportarArchivoExcel(ini);
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
     PrincipalAdministrador.escritorio.add(form1);
     form1.setLocation((screenSize.width - form1.getSize().width) / 2, (screenSize.height - form1.getSize().height) / 2);
     form1.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem17MouseClicked
        try {
            FManifestarPedidosEnRuta form1 = new FManifestarPedidosEnRuta(this.ini);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            PrincipalAdministrador.escritorio.add(form1);
            form1.setLocation((screenSize.width - form1.getSize().width) / 2, (screenSize.height - form1.getSize().height) / 2);
            form1.show();
        } catch (Exception ex) {
            Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17MouseClicked

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
    try{
       FManifestarPedidosEnRuta form1 = new FManifestarPedidosEnRuta(ini);
      Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
     this.escritorio.add(form1);
     form1.setLocation((screenSize.width - form1.getSize().width) / 2, (screenSize.height - form1.getSize().height) / 2);
     form1.show(); 
    }catch(Exception ex){
         Logger.getLogger(PrincipalAdministrador.class.getName()).log(Level.SEVERE, null, ex); 
    }
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalAdministrador().setVisible(true);
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("aplicacionlogistica/configuracion/imagenes/turbo_64x64.png"));
        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenu jMenuAdministracion;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu jMenuLogistica;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuAsignarDocumentos;
    private javax.swing.JMenuItem menuCambiarClave;
    private javax.swing.JMenuItem menuIngresarEmpleados;
    private javax.swing.JMenuItem menuIngresarUsuarios;
    private javax.swing.JMenu mnuCarros;
    private javax.swing.JMenuItem mnuCrearCentrosDeCosto;
    private javax.swing.JMenuItem mnuCrearDocumentos;
    private javax.swing.JMenu mnuDocumentos;
    private javax.swing.JMenu mnuIngresarCarros;
    // End of variables declaration//GEN-END:variables
}
