/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogistica.administrativo;


import aplicacionlogistica.configuracion.CambiarClave;
import aplicacionlogistica.configuracion.Inicio;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarDocumentosEmpleados;
import aplicacionlogistica.distribucion.formularios.administracion.IngresarUsuarios;
import aplicacionlogistica.distribucion.formularios.reportes.rptDocumentosEmpleados;
import aplicacionlogistica.distribucion.objetos.personas.CUsuarios;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author VLI_488
 */
public class PrincipalSeguridad extends javax.swing.JFrame {

    Inicio ini=null;
    CUsuarios user;
 

    public void setUser(CUsuarios user) {
        this.user = user;
    }

    public CUsuarios getUser() {
        return user;
    }

    
    
    public PrincipalSeguridad() {
        initComponents();
        
    }
   
    public PrincipalSeguridad(Inicio ini) throws Exception {
        
            initComponents();
            this.ini= ini;
            this.user=ini.getUser();
            this.setSize(ini.getDimension());
            this.setLocation(0,0);
            this.setTitle("Sistema de Información Logistica    -- Usuario de Sistema: " + user.getNombres() + " " + user.getApellidos() );
          
            if(user.getClaveUsuario().equals(Inicio.cifrar("123456"))){ // cuando el usuario es nuevo
                this.escritorio.setSize(600, 400);
                 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                 CambiarClave form= new CambiarClave(ini);
                 PrincipalSeguridad.escritorio.add(form);
                 form.setSize(escritorio.getSize());
                 form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
                 jMenuBar1.setVisible(false);
                 form.show();
                 
           }else{
                this.escritorio.setSize(600, 400);
                 Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                 CambiarClave form= new CambiarClave(ini);
                 PrincipalSeguridad.escritorio.add(form);
                 form.setSize(escritorio.getSize());
                 form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
                 jMenuBar1.setVisible(true);
            }
       
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuCambiarClave = new javax.swing.JMenuItem();
        jMenuAdministracion = new javax.swing.JMenu();
        menuIngresarEmpleados = new javax.swing.JMenuItem();
        menuIngresarUsuarios = new javax.swing.JMenuItem();
        jMenuLogistica = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuAsignarDocumentos = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        menuRptDocumentosEmpleados = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        escritorio.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);

        jMenuBar1.setEnabled(false);

        menuArchivo.setText("Archivo");
        menuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoActionPerformed(evt);
            }
        });

        menuCambiarClave.setText("Cambio de Clave");
        menuCambiarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCambiarClaveActionPerformed(evt);
            }
        });
        menuArchivo.add(menuCambiarClave);

        jMenuBar1.add(menuArchivo);

        jMenuAdministracion.setText("Administracion");

        menuIngresarEmpleados.setText("Empleados");
        menuIngresarEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIngresarEmpleadosMouseClicked(evt);
            }
        });
        menuIngresarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarEmpleadosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(menuIngresarEmpleados);

        menuIngresarUsuarios.setText("Usuarios de Sistema");
        menuIngresarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIngresarUsuariosActionPerformed(evt);
            }
        });
        jMenuAdministracion.add(menuIngresarUsuarios);

        jMenuBar1.add(jMenuAdministracion);

        jMenuLogistica.setText("Logistica");

        jMenu2.setText("Empleados");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuAsignarDocumentos.setText("Asignar Documentos");
        menuAsignarDocumentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAsignarDocumentosMouseClicked(evt);
            }
        });
        menuAsignarDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignarDocumentosActionPerformed(evt);
            }
        });
        jMenu2.add(menuAsignarDocumentos);

        jMenuLogistica.add(jMenu2);

        jMenuBar1.add(jMenuLogistica);

        jMenuReportes.setText("Reportes");

        menuRptDocumentosEmpleados.setText("Reporte Documentos Empleados");
        menuRptDocumentosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRptDocumentosEmpleadosActionPerformed(evt);
            }
        });
        jMenuReportes.add(menuRptDocumentosEmpleados);

        jMenuBar1.add(jMenuReportes);

        jMenu1.setText("jMenu1");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuIngresarEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIngresarEmpleadosMouseClicked


    }//GEN-LAST:event_menuIngresarEmpleadosMouseClicked

    private void menuIngresarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarEmpleadosActionPerformed
      // ini= new Inicio(usuario);
//       IngresarEmpleados form= new IngresarEmpleados();
//       PrincipalSeguridad.escritorio.add(form);
//       form.setSize(escritorio.getSize());
//        form.setListaDeAgencias(arrAgenciass);
//        form.setListaDeCargos(arrCargos);
//        form.setListaDeCentrosDeCosto(arrCentrosDeCosto);
//        form.setListaDeCiudades(arrCiudades);
//        form.setListaDeDepartamentos(arrDepartamentos);
//        form.setListaDeEntidadesBancarias(arrEntidadesBancarias);
//        form.setListaDeEstadosCiviles(arrEstadosCiviles);
//        form.setListaDeRegionales(arrRegionales);
//        form.setListaDeTiposContratosPer(arrTiposContratos);
//        form.setListaDeTiposDeSangre(arrTiposDeSangre);
//        form.setListaDeZonas(arrZonas);
        
//       form.show();
    }//GEN-LAST:event_menuIngresarEmpleadosActionPerformed

    private void menuAsignarDocumentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignarDocumentosMouseClicked
      switch(user.getTipoAcceso()){
          case 1: // no tiene acceso
              
              break;
          case 2: // acceso total
              switch(user.getNivelAcceso()){
                  case 1:
                      
                      break;
                  case 2:
                      
                      break;
                  case 3:
                      
                      break;
                  case 4:
                      
                      break;    
                  
              }
              break;
          case 3: // acceso a nivel Administrativo
              switch(user.getNivelAcceso()){
                  case 1:
                      
                      break;
                  case 2:
                      
                      break;
                  case 3:
                      
                      break;
                  case 4:
                      
                      break;    
                  
              }
          case 4: // Acceso a nivel de seguridad
              switch(user.getNivelAcceso()){
                  case 1:
                      
                      break;
                  case 2:
                      
                      break;
                  case 3:
                      
                      break;
                  case 4:
                      
                      break;    
                  
              }
            case 5: // Acceso a nivel de Operativo
              switch(user.getNivelAcceso()){
                  case 1:
                      
                      break;
                  case 2:
                      
                      break;
                  case 3:
                      
                      break;
                  case 4:
                      
                      break;    
                  
              }
          default:
      }
    }//GEN-LAST:event_menuAsignarDocumentosMouseClicked

    private void menuAsignarDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignarDocumentosActionPerformed
              IngresarDocumentosEmpleados form1= new IngresarDocumentosEmpleados(ini);
              PrincipalSeguridad.escritorio.add(form1);
              form1.setSize(escritorio.getSize());
              form1.show();
              
        switch(ini.getTipoDeacceso()){
          case 0:
              break;
          case 1:
             
              break;
          case 2:
//              IngresarDocumentosEmpleados form1= new IngresarDocumentosEmpleados(this.ini);
//              Principal.escritorio.add(form1);
//              form1.setSize(escritorio.getSize());
//              form1.show();
//              break;
          case 3:
              break;
          case 4:
              break;
          default:
              break;
      }
       
    }//GEN-LAST:event_menuAsignarDocumentosActionPerformed

    private void menuIngresarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIngresarUsuariosActionPerformed
       switch(ini.getTipoDeacceso()){
          case 0:
              break;
          case 1:
              IngresarUsuarios form;
       try {
//              form = new IngresarUsuarios();
//              PrincipalSeguridad.escritorio.add(form);
//              form.setSize(escritorio.getSize());
//              form.show();       
       } catch (Exception ex) {
           Logger.getLogger(PrincipalSeguridad.class.getName()).log(Level.SEVERE, null, ex);
       }
              
              break;
          case 2:
              break;
          case 3:
              break;
          case 4:
              break;
          default:
              break;
      }
       
    }//GEN-LAST:event_menuIngresarUsuariosActionPerformed

    private void menuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoActionPerformed
       
    }//GEN-LAST:event_menuArchivoActionPerformed

    private void menuCambiarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCambiarClaveActionPerformed
        try {
            this.escritorio.setSize(600, 400);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            CambiarClave form= new CambiarClave(ini);
            PrincipalSeguridad.escritorio.add(form);
            form.setSize(escritorio.getSize());
            form.setLocation ((screenSize.width - escritorio.getSize().width) / 2,(screenSize.height - escritorio.getSize().height) / 2);
            form.show();
        } catch (Exception ex) {
            Logger.getLogger(PrincipalSeguridad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuCambiarClaveActionPerformed

    private void menuRptDocumentosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRptDocumentosEmpleadosActionPerformed
             rptDocumentosEmpleados form;
            form = new rptDocumentosEmpleados(this.ini);
              PrincipalSeguridad.escritorio.add(form);
              form.setSize(escritorio.getSize());
              form.show();   
    }//GEN-LAST:event_menuRptDocumentosEmpleadosActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
          try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new PrincipalSeguridad().setVisible(true);
                
            }
        });
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("aplicacionlogistica/imagenes/turbo_64x64.png"));


        return retValue;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAdministracion;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuLogistica;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuAsignarDocumentos;
    private javax.swing.JMenuItem menuCambiarClave;
    private javax.swing.JMenuItem menuIngresarEmpleados;
    private javax.swing.JMenuItem menuIngresarUsuarios;
    private javax.swing.JMenuItem menuRptDocumentosEmpleados;
    // End of variables declaration//GEN-END:variables
}
