/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chart.main;

import chart.barChart.BarModelChart;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author RAVEN
 */
public class BarMain extends javax.swing.JFrame {
 public BarMain(String titulo) {
      initComponents();
      getContentPane().setBackground(new Color(250, 250, 250));
 }
   
    public BarMain() {
        try {
            initComponents();
            getContentPane().setBackground(new Color(250, 250, 250));
            lblFecha.setText("2022-09-03");

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://190.144.23.186:3306/comercializadoracam?useTimezone=true&serverTimezone=UTC&useSSL=false", "luislopez", "jslslpzmjc1212");
            Statement stmt = con.createStatement();

            String sql = "select m.vehiculo,count(numeroFactura) as cant "
                    + "from facturaspormanifiesto fm "
                    + "join manifiestosdedistribucion m on m.consecutivo = fm.numeroManifiesto "
                    + "where "
                    + "m.fechaDistribucion ='2022-09-03' "
                    + "group by m.vehiculo;";

            ResultSet rs = stmt.executeQuery(sql);
            int i = 0;
            int k = 1;
            while (rs.next()) {
                chart.addLegend(rs.getString("vehiculo"), getColor(i++));
                if (i == 26) {
                    i = 0;
                }
                k++;
            }
            rs.beforeFirst();
            i = 0;
            double[] lista = new double[k];
            while (rs.next()) {
                lista[i] = rs.getDouble("cant");
                i++;
            }
            chart.addData(new BarModelChart("", lista));
         
            con.close();
            stmt.close();
            rs.close();

            //
            //        chart.addLegend("Expense", new Color(135, 189, 245));
            //        chart.addLegend("Profit", new Color(189, 135, 245));
            //        chart.addLegend("Cost", new Color(139, 229, 222));
            //
            //chart.addData(new BarModelChart("January", new double[]{500, 200, 80,89}));
            //chart.addData(new BarModelChart("February", new double[]{600, 750, 90,150}));
            //chart.addData(new BarModelChart("March", new double[]{200, 350, 460,900}));
            //chart.addData(new BarModelChart("April", new double[]{480, 150, 750,700}));
            //chart.addData(new BarModelChart("May", new double[]{350, 540, 300,150}));
            //chart.addData(new BarModelChart("June", new double[]{190, 280, 81,200}));
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BarMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BarMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new chart.barChart.BarChart();
        lblFecha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblFecha.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTitulo.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
        lblTitulo.setText("Grafica de pedidos movilizados por Vehiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        chart.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarMain().setVisible(true);
            }
        });
    }

    private Color getColor(int index) {
        Color color = new Color(255,255,255);
        switch (index) {
            case 0:
                color = new Color(69, 120, 177);
                break;
            case 1:
                color = new Color(236, 217, 21);
                break;
            case 2:
                color = new Color(179, 238, 154);
                break;
            case 3:
                color = new Color(99, 149, 202);
                break;
            case 4:
                color = new Color(241, 134, 191);
                break;
            case 5:
                color = new Color(162, 249, 52);
                break;
            case 6:
                color = new Color(199, 247, 255);
                break;
             case 7:
                color = new Color(241,165,89);
                break;   
            case 8:
                 color = new Color(186, 255, 182);
              
                break;
            case 9:
               color = new Color(206, 17, 253);
                break;
            case 10:
                color = new Color(210, 211, 111);
                break;
            case 11:
                color = new Color(240, 225, 232);
                break;
            case 12:
                color = new Color(255,255,190);
                break;
            case 13:
                color = new Color(225, 107, 97);
                break;
            case 14:
                color = new Color(178, 183, 246);
                break;
            case 15:
                color = new Color(153, 231, 150);
                break;
            case 16:
                color = new Color(255,255,138);
                break;
            case 17:
                color = new Color(225, 196, 209);
                break;
            case 18:
                color = new Color(241, 139, 126);
                break;
            case 19:
                color = new Color(231, 231, 143);
                break;
            case 20:
                color = new Color(209, 167, 186);
                break;
            case 21:
                color = new Color(167, 213, 237);
                break;
            case 22:
                 color = new Color(143,227,255);
                break;
            case 23:
                color = new Color(240, 239, 176);
                break;
            case 24:
                color = new Color(120, 207, 119);
                break;
            case 25:
                color = new Color(134, 181, 220);
                break;
            case 26:
                color = new Color(255, 171, 157);
                break;
           case 27:
                color = new Color(255, 242, 205);
                break;
                case 28:
                color = new Color(222, 179, 223);
                break;
                case 29:
                color = new Color(166, 161, 237);
                break;
                case 30:
                color = new Color(186, 213, 249);
                break;
                case 31:
                color = new Color(255, 213, 178);
                break;
                case 32:
                color = new Color(255, 171, 157);
                break;
                

        }

        return color; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chart.barChart.BarChart chart;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
