/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogistica.distribucion.formularios;


import aplicacionlogistica.configuracion.Inicio;
import aplicacionlogistica.distribucion.objetos.CDocumentos;
import aplicacionlogistica.distribucion.objetos.personas.CUsuarios;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FIngresarConsignacionesRutas  extends javax.swing.JInternalFrame {
 KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
Object[] fila = new Object[4];
DefaultTableModel modelo;
CUsuarios user;
String usuario;
boolean actualizar=false;
Inicio ini;
String mensaje;
    

//private FResidentes residente = (FResidentes)this.getParent();//
    /**
     * Creates new form FBuscar2
     */
    public FIngresarConsignacionesRutas() {
        initComponents();
         txtNumeroManifiesto.requestFocus();
    }
 public FIngresarConsignacionesRutas(Inicio ini) {
        initComponents();
        this.ini=ini;
        this.user=ini.getUser();
        this.setResizable(false);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation ((screenSize.width - this.getSize().width) / 2,(screenSize.height - this.getSize().height) / 2);
       manager.addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                //como dije, solo las notificaciones del tipo "typed" son las que actualizan los componentes
                if (e.getID() == KeyEvent.KEY_TYPED) {
                    // if(e.getSource() instanceof JComponent 
                    //if(e.getKeyChar()>='0' && e.getKeyChar()<='9' ){
                    if (e.getSource() instanceof JComponent
                            // si el textfield esta marcado en el nombre y si el nombre es igual a "ignore_upper_case"
                            // entonces el campo puede tomar las minusculas
                            && ((JComponent) e.getSource()).getName() != null
                            && ((JComponent) e.getSource()).getName().startsWith("numerico")) {

                        if (e.getKeyChar() >= '0' && e.getKeyChar() <= '9') {
                            return false;
                        } else {
                            return true;
                        }

                    } else {
                        if (e.getKeyChar() >= 'a' && e.getKeyChar() <= 'z') {
                            if (e.getSource() instanceof JComponent
                                    // si el textfield esta marcado en el nombre y si el nombre es igual a "ignore_upper_case"
                                    // entonces el campo puede tomar las minusculas
                                    && ((JComponent) e.getSource()).getName() != null
                                    && ((JComponent) e.getSource()).getName().startsWith("minuscula")) {
                                return false;
                            } else {
                                //como vamos a convertir todo a mayúsculas, entonces solo checamos si los caracteres son 
                                //minusculas                          
                                e.setKeyChar((char) (((int) e.getKeyChar()) - 32));
                            }
                        }
                    }
                }

                //y listo, regresamos siempre falso para que las demas notificaciones continuen, si regresamos true
                // significa que el dispatcher consumio el evento
                return false;
            }
        });        
        txtNumeroManifiesto.setEnabled(false);
        //jLabel2.setVisible(false);
         for(CDocumentos obj : this.ini.getArrTiposDocumentos()){
                    fila = new Object[4];
                    fila[0] = obj.getIdtiposDocumentos();
                    fila[1] = obj.getNombreTipoDocumento();
                    fila[2] = obj.getFormato();
                    if(obj.getActivoDocumento()<1){
                       fila[3] = false;
                    }else{
                       fila[3] = true; 
                    }
                    modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(fila);
          }
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroManifiesto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNumeroSoporte = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxEntidadesBancarias = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroDeCuenta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMedioDePago = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Formulario para el ingreso de Documentos al Sistema");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/turbo_64x64.png"))); // NOI18N

        jLabel1.setText("numero Manifiesto");

        txtNumeroManifiesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroManifiestoFocusGained(evt);
            }
        });
        txtNumeroManifiesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroManifiestoActionPerformed(evt);
            }
        });
        txtNumeroManifiesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroManifiestoKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Documento", "Banco", "Numero Cuenta", "Medio de Pago", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(130);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        txtNumeroSoporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroSoporteFocusGained(evt);
            }
        });
        txtNumeroSoporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroSoporteKeyPressed(evt);
            }
        });

        jLabel3.setText("numero Soporte");

        cbxEntidadesBancarias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Entidad Bancaria");

        jLabel5.setText("numero Cuenta");

        txtNumeroDeCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroDeCuentaFocusGained(evt);
            }
        });
        txtNumeroDeCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumeroDeCuentaKeyPressed(evt);
            }
        });

        jLabel6.setText("Medio de pago");

        txtMedioDePago.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMedioDePagoFocusGained(evt);
            }
        });
        txtMedioDePago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMedioDePagoKeyPressed(evt);
            }
        });

        jLabel7.setText("Valor");

        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtValorFocusGained(evt);
            }
        });
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/16x16/OK.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroManifiesto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxEntidadesBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroManifiesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxEntidadesBancarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Salir de ingresar empleado...");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(97, 97));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/cancel-64x64.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Limpia la ventana para ingreasr registro...");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(97, 97));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/agregar.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Agregar ó Modificar un registro");
        btnNuevo.setEnabled(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPreferredSize(new java.awt.Dimension(97, 97));
        btnNuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/grabar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setToolTipText("Guardar registro nuevo ó modificado");
        btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar.setPreferredSize(new java.awt.Dimension(97, 97));
        btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 260, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int row=jTable1.getSelectedRow();
        txtNumeroManifiesto.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        //jLabel2.setText("Id. Documento :  " + String.valueOf(jTable1.getValueAt(row, 0)));
        //jLabel2.setVisible(true);
        txtNumeroSoporte.setText(String.valueOf(jTable1.getValueAt(row, 2)));
        if((Boolean) jTable1.getModel().getValueAt(row,3)){
            //chkActivo.setText("Documento Activo");
           // chkActivo.setSelected(true);
        }else{
            //chkActivo.setText("Documento no Activo");
            //chkActivo.setSelected(false);
        }
        actualizar=true;
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/actualizar_64x64.png"))); // NOI18N
        btnNuevo.setText("Actualizar");
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtNumeroManifiestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroManifiestoKeyPressed

//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            ArrayList<String> list = new ArrayList();
//            txtNombreDocumento.setEnabled(false);
//            try {
//                CEmpleados  empl = new CEmpleados(usuario);
//                list= empl.buscarEmpleados(txtNombreDocumento.getText());
//                for(String obj : list){
//                    CEmpleados empleado= new CEmpleados(usuario, obj.toString());
//                    fila = new Object[3];
//                    fila[0] = empleado.getCedula();
//                    fila[1] = empleado.getNombres();
//                    fila[2] = empleado.getApellidos();
//                    modelo = (DefaultTableModel) jTable1.getModel();
//                    modelo.addRow(fila);
//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(FCrearCargos.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (Exception ex) {
//                Logger.getLogger(FCrearCargos.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }//GEN-LAST:event_txtNumeroManifiestoKeyPressed

    private void txtNumeroManifiestoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroManifiestoFocusGained
        txtNumeroManifiesto.setSelectionStart(0);
        txtNumeroManifiesto.setSelectionEnd(txtNumeroManifiesto.getText().length());
    }//GEN-LAST:event_txtNumeroManifiestoFocusGained

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       actualizar=false;
       txtNumeroManifiesto.setText("");
       //chkActivo.setEnabled(false);
       //chkActivo.setSelected(false);
       //jLabel2.setVisible(false);
       btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/imagenes/agregar.png"))); // NOI18N
       btnNuevo.setText("Nuevo");
       btnNuevo.setEnabled(true);
       jTable1.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if (actualizar) {
           btnNuevo.setEnabled(false);
           txtNumeroManifiesto.setEnabled(true);
           //chkActivo.setEnabled(true);
           btnNuevo.setEnabled(false);

        } else {
           txtNumeroManifiesto.setEnabled(true);
           txtNumeroManifiesto.requestFocus();
           //chkActivo.setSelected(true);
           jTable1.setEnabled(false);
           btnNuevo.setEnabled(false);
        }
        //txtCedula.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (!txtNumeroManifiesto.getText().isEmpty()) {
            int x = JOptionPane.showConfirmDialog(this, "Desea guardar el registro ?", "Guardar registro", 0);
            if (x == 0) {
             if(actualizar){
                  if (validar()) {
                    if (actualizarRegistroCargo()) {
                       // new Thread(new HiloGuardarEmpleado(5,empleadoNuevo)).start();
                        JOptionPane.showInternalMessageDialog(this, "El registro del empleado ha sido actualizado perfectamente", "Registro actualizado", 1);
                       
                        habilitar(false);

                    } else {
                        JOptionPane.showInternalMessageDialog(this, "Se presentó un error al guardar el regisstro", "Error al guardar", 0);
                    }

                } else {
                    JOptionPane.showInternalMessageDialog(this, "mensaje", "Error al guardar", 0);
                } 
             }else{
                if (validar()) {
                    if (guardarRegistroDocumento()) {
                       // new Thread(new HiloGuardarEmpleado(5,empleadoNuevo)).start();
                        JOptionPane.showInternalMessageDialog(this, "El registro del empleado ha sido guardado perfectamente", "Registro guardado", 1);
                       
                        habilitar(false);

                    } else {
                        JOptionPane.showInternalMessageDialog(this, "Se presentó un error al guardar el regisstro", "Error al guardar", 0);
                    }

                } else {
                    JOptionPane.showInternalMessageDialog(this, "mensaje", "Error al guardar", 0);
                } 
             }
                
            
            }
        } else {
            JOptionPane.showInternalMessageDialog(this, "No se pueden Guardar Datos con campos vacíos", "Error al guardar", 2);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void txtNumeroSoporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroSoporteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSoporteFocusGained

    private void txtNumeroSoporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroSoporteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroSoporteKeyPressed

    private void txtNumeroManifiestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroManifiestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroManifiestoActionPerformed

    private void txtNumeroDeCuentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDeCuentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeCuentaFocusGained

    private void txtNumeroDeCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDeCuentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeCuentaKeyPressed

    private void txtMedioDePagoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMedioDePagoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedioDePagoFocusGained

    private void txtMedioDePagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedioDePagoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedioDePagoKeyPressed

    private void txtValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFocusGained

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxEntidadesBancarias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txtMedioDePago;
    public javax.swing.JTextField txtNumeroDeCuenta;
    public javax.swing.JTextField txtNumeroManifiesto;
    public javax.swing.JTextField txtNumeroSoporte;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
 public boolean validar() {
        boolean verificado = true;
        mensaje = "";
        if (txtNumeroManifiesto.getText().isEmpty()) {
            mensaje += "No ha colocado el nombre del Documento" + "  \n";
            verificado = false;
        }
    
    return verificado;
    
}
private boolean guardarRegistroDocumento(){
     boolean valida=false;
    try {
       
          CDocumentos documento = new CDocumentos(ini);  
          documento.setNombreTipoDocumento(txtNumeroManifiesto.getText().trim());
          documento.setFormato(txtNumeroSoporte.getText());
//          if(chkActivo.isSelected()){
//           documento.setActivoDocumento(1);
//          }else{
//               documento.setActivoDocumento(1);
//          }
          valida=documento.grabarTiposDocumentos();
          if(valida){
             
//             jLabel2.setVisible(true);
//             jLabel2.setText("Id. Documento :  " + documento.getIdtiposDocumentos());  
              fila = new Object[4];
                    fila[0] = documento.getIdtiposDocumentos();
                    fila[1] = documento.getNombreTipoDocumento();
                    fila[2] = documento.getFormato();
                    if(documento.getActivoDocumento()<1){
                       fila[3] = false;
                    }else{
                       fila[3] = true; 
                    }
                    modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(fila);
          }
         
          
    } catch (Exception ex) {
        Logger.getLogger(FIngresarConsignacionesRutas.class.getName()).log(Level.SEVERE, null, ex);
    }
    return valida;
}

private boolean actualizarRegistroCargo(){
     boolean valida=false;
    try {
         int row=jTable1.getSelectedRow();
         //jLabel2.setText("Id. Documento :  " + String.valueOf(jTable1.getValueAt(row, 0)));
          CDocumentos documento = new CDocumentos(ini); 
          documento.setIdtiposDocumentos((Integer)jTable1.getValueAt(row, 0));
          documento.setNombreTipoDocumento(txtNumeroManifiesto.getText().trim());
          documento.setFormato(txtNumeroSoporte.getText().trim());
//          if(chkActivo.isSelected()){
//           documento.setActivoDocumento(1);
//          }else{
//               documento.setActivoDocumento(0);
//          }
         
          valida=documento.actualizarDocumentos(1);
          
           if(valida){
             jTable1.setValueAt(documento.getNombreTipoDocumento(), row, 1);
            // jLabel2.setVisible(true);
            // jLabel2.setText("Id. Documento :  " + documento.getIdtiposDocumentos());  
          }
    } catch (Exception ex) {
        Logger.getLogger(FIngresarConsignacionesRutas.class.getName()).log(Level.SEVERE, null, ex);
    }return valida;
}

private boolean habilitar(boolean valor){
     boolean valida=false;
    
    return valida; 
}
}
