/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionlogistica.distribucion.formularios.administracion;


import aplicacionlogistica.configuracion.Inicio;
import aplicacionlogistica.distribucion.objetos.CDocumentos;
import aplicacionlogistica.distribucion.objetos.personas.CUsuarios;
import java.awt.Dimension;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FCrearDocumentos  extends javax.swing.JInternalFrame {
 KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
Object[] fila = new Object[4];
DefaultTableModel modelo;
CUsuarios user;
String usuario;
boolean actualizar=false;
Inicio ini;
String mensaje;
    

//private FResidentes residente = (FResidentes)this.getParent();//
    /**
     * Creates new form FBuscar2
     */
    public FCrearDocumentos() {
        initComponents();
         txtNombreDocumento.requestFocus();
    }
 public FCrearDocumentos(Inicio ini) {
        initComponents();
        this.ini=ini;
        this.user=ini.getUser();
        this.setResizable(false);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation ((screenSize.width - this.getSize().width) / 2,(screenSize.height - this.getSize().height) / 2);
       manager.addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                //como dije, solo las notificaciones del tipo "typed" son las que actualizan los componentes
                if (e.getID() == KeyEvent.KEY_TYPED) {
                    // if(e.getSource() instanceof JComponent 
                    //if(e.getKeyChar()>='0' && e.getKeyChar()<='9' ){
                    if (e.getSource() instanceof JComponent
                            // si el textfield esta marcado en el nombre y si el nombre es igual a "ignore_upper_case"
                            // entonces el campo puede tomar las minusculas
                            && ((JComponent) e.getSource()).getName() != null
                            && ((JComponent) e.getSource()).getName().startsWith("numerico")) {

                        if (e.getKeyChar() >= '0' && e.getKeyChar() <= '9') {
                            return false;
                        } else {
                            return true;
                        }

                    } else {
                        if (e.getKeyChar() >= 'a' && e.getKeyChar() <= 'z') {
                            if (e.getSource() instanceof JComponent
                                    // si el textfield esta marcado en el nombre y si el nombre es igual a "ignore_upper_case"
                                    // entonces el campo puede tomar las minusculas
                                    && ((JComponent) e.getSource()).getName() != null
                                    && ((JComponent) e.getSource()).getName().startsWith("minuscula")) {
                                return false;
                            } else {
                                //como vamos a convertir todo a mayúsculas, entonces solo checamos si los caracteres son 
                                //minusculas                          
                                e.setKeyChar((char) (((int) e.getKeyChar()) - 32));
                            }
                        }
                    }
                }

                //y listo, regresamos siempre falso para que las demas notificaciones continuen, si regresamos true
                // significa que el dispatcher consumio el evento
                return false;
            }
        });        
        txtNombreDocumento.setEnabled(false);
        jLabel2.setVisible(false);
         for(CDocumentos obj : this.ini.getArrTiposDocumentos()){
                    fila = new Object[4];
                    fila[0] = obj.getIdtiposDocumentos();
                    fila[1] = obj.getNombreTipoDocumento();
                    fila[2] = obj.getFormato();
                    if(obj.getActivoDocumento()<1){
                       fila[3] = false;
                    }else{
                       fila[3] = true; 
                    }
                    modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(fila);
          }
 }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreDocumento = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        chkActivo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtFormato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Formulario para el ingreso de Documentos al Sistema");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/turbo_64x64.png"))); // NOI18N

        jLabel1.setText("Nombre del  Documento");

        txtNombreDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreDocumentoFocusGained(evt);
            }
        });
        txtNombreDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreDocumentoKeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Documento", "Nombre Documento", "Formato", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        chkActivo.setEnabled(false);
        chkActivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkActivoStateChanged(evt);
            }
        });
        chkActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActivoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Id. Documento : ");

        txtFormato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormatoFocusGained(evt);
            }
        });
        txtFormato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormatoKeyPressed(evt);
            }
        });

        jLabel3.setText("Formato");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/exit.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Salir de ingresar empleado...");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setPreferredSize(new java.awt.Dimension(97, 97));
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/cancel-64x64.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Limpia la ventana para ingreasr registro...");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPreferredSize(new java.awt.Dimension(97, 97));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/agregar.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Agregar ó Modificar un registro");
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setPreferredSize(new java.awt.Dimension(97, 97));
        btnNuevo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/grabar.png"))); // NOI18N
        btnGrabar.setText("Grabar");
        btnGrabar.setToolTipText("Guardar registro nuevo ó modificado");
        btnGrabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar.setPreferredSize(new java.awt.Dimension(97, 97));
        btnGrabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGrabar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkActivo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(txtNombreDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(5, 5, 5))
                    .addComponent(chkActivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        int row=jTable1.getSelectedRow();
        txtNombreDocumento.setText(String.valueOf(jTable1.getValueAt(row, 1)));
        jLabel2.setText("Id. Documento :  " + String.valueOf(jTable1.getValueAt(row, 0)));
        jLabel2.setVisible(true);
        txtFormato.setText(String.valueOf(jTable1.getValueAt(row, 2)));
        if((Boolean) jTable1.getModel().getValueAt(row,3)){
            chkActivo.setText("Documento Activo");
            chkActivo.setSelected(true);
        }else{
            chkActivo.setText("Documento no Activo");
            chkActivo.setSelected(false);
        }
        actualizar=true;
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/actualizar_64x64.png"))); // NOI18N
        btnNuevo.setText("Actualizar");
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtNombreDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDocumentoKeyPressed

//        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            ArrayList<String> list = new ArrayList();
//            txtNombreDocumento.setEnabled(false);
//            try {
//                CEmpleados  empl = new CEmpleados(usuario);
//                list= empl.buscarEmpleados(txtNombreDocumento.getText());
//                for(String obj : list){
//                    CEmpleados empleado= new CEmpleados(usuario, obj.toString());
//                    fila = new Object[3];
//                    fila[0] = empleado.getCedula();
//                    fila[1] = empleado.getNombres();
//                    fila[2] = empleado.getApellidos();
//                    modelo = (DefaultTableModel) jTable1.getModel();
//                    modelo.addRow(fila);
//                }
//
//            } catch (SQLException ex) {
//                Logger.getLogger(FCrearCargos.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (Exception ex) {
//                Logger.getLogger(FCrearCargos.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
    }//GEN-LAST:event_txtNombreDocumentoKeyPressed

    private void txtNombreDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDocumentoFocusGained
        txtNombreDocumento.setSelectionStart(0);
        txtNombreDocumento.setSelectionEnd(txtNombreDocumento.getText().length());
    }//GEN-LAST:event_txtNombreDocumentoFocusGained

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       actualizar=false;
       txtNombreDocumento.setText("");
       chkActivo.setEnabled(false);
       chkActivo.setSelected(false);
       jLabel2.setVisible(false);
       btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionlogistica/configuracion/imagenes/agregar.png"))); // NOI18N
       btnNuevo.setText("Nuevo");
       btnNuevo.setEnabled(true);
       jTable1.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        if (actualizar) {
           btnNuevo.setEnabled(false);
           txtNombreDocumento.setEnabled(true);
           chkActivo.setEnabled(true);
           btnNuevo.setEnabled(false);

        } else {
           txtNombreDocumento.setEnabled(true);
           txtNombreDocumento.requestFocus();
           chkActivo.setSelected(true);
           jTable1.setEnabled(false);
           btnNuevo.setEnabled(false);
        }
        //txtCedula.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (!txtNombreDocumento.getText().isEmpty()) {
            int x = JOptionPane.showConfirmDialog(this, "Desea guardar el registro ?", "Guardar registro", 0);
            if (x == 0) {
             if(actualizar){
                  if (validar()) {
                    if (actualizarRegistroCargo()) {
                       // new Thread(new HiloGuardarEmpleado(5,empleadoNuevo)).start();
                        JOptionPane.showInternalMessageDialog(this, "El registro del empleado ha sido actualizado perfectamente", "Registro actualizado", 1);
                       
                        habilitar(false);

                    } else {
                        JOptionPane.showInternalMessageDialog(this, "Se presentó un error al guardar el regisstro", "Error al guardar", 0);
                    }

                } else {
                    JOptionPane.showInternalMessageDialog(this, "mensaje", "Error al guardar", 0);
                } 
             }else{
                if (validar()) {
                    if (guardarRegistroDocumento()) {
                       // new Thread(new HiloGuardarEmpleado(5,empleadoNuevo)).start();
                        JOptionPane.showInternalMessageDialog(this, "El registro del empleado ha sido guardado perfectamente", "Registro guardado", 1);
                       
                        habilitar(false);

                    } else {
                        JOptionPane.showInternalMessageDialog(this, "Se presentó un error al guardar el regisstro", "Error al guardar", 0);
                    }

                } else {
                    JOptionPane.showInternalMessageDialog(this, "mensaje", "Error al guardar", 0);
                } 
             }
                
            
            }
        } else {
            JOptionPane.showInternalMessageDialog(this, "No se pueden Guardar Datos con campos vacíos", "Error al guardar", 2);
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void chkActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActivoActionPerformed
        if(chkActivo.isSelected()){
            chkActivo.setText("Documento activo");
        }else{
             chkActivo.setText("Documento No Activo");
        }
    }//GEN-LAST:event_chkActivoActionPerformed

    private void chkActivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkActivoStateChanged
        if(chkActivo.isSelected()){
            chkActivo.setText("Documento activo");
        }else{
             chkActivo.setText("Documento No Activo");
        }
    }//GEN-LAST:event_chkActivoStateChanged

    private void txtFormatoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormatoFocusGained

    private void txtFormatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormatoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormatoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField txtFormato;
    public javax.swing.JTextField txtNombreDocumento;
    // End of variables declaration//GEN-END:variables
 public boolean validar() {
        boolean verificado = true;
        mensaje = "";
        if (txtNombreDocumento.getText().isEmpty()) {
            mensaje += "No ha colocado el nombre del Documento" + "  \n";
            verificado = false;
        }
    
    return verificado;
    
}
private boolean guardarRegistroDocumento(){
     boolean valida=false;
    try {
       
          CDocumentos documento = new CDocumentos(ini);  
          documento.setNombreTipoDocumento(txtNombreDocumento.getText().trim());
          documento.setFormato(txtFormato.getText());
          if(chkActivo.isSelected()){
           documento.setActivoDocumento(1);
          }else{
               documento.setActivoDocumento(1);
          }
          valida=documento.grabarTiposDocumentos();
          if(valida){
             
             jLabel2.setVisible(true);
             jLabel2.setText("Id. Documento :  " + documento.getIdtiposDocumentos());  
              fila = new Object[4];
                    fila[0] = documento.getIdtiposDocumentos();
                    fila[1] = documento.getNombreTipoDocumento();
                    fila[2] = documento.getFormato();
                    if(documento.getActivoDocumento()<1){
                       fila[3] = false;
                    }else{
                       fila[3] = true; 
                    }
                    modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(fila);
          }
         
          
    } catch (Exception ex) {
        Logger.getLogger(FCrearDocumentos.class.getName()).log(Level.SEVERE, null, ex);
    }
    return valida;
}

private boolean actualizarRegistroCargo(){
     boolean valida=false;
    try {
         int row=jTable1.getSelectedRow();
         jLabel2.setText("Id. Documento :  " + String.valueOf(jTable1.getValueAt(row, 0)));
          CDocumentos documento = new CDocumentos(ini); 
          documento.setIdtiposDocumentos((Integer)jTable1.getValueAt(row, 0));
          documento.setNombreTipoDocumento(txtNombreDocumento.getText().trim());
          documento.setFormato(txtFormato.getText().trim());
          if(chkActivo.isSelected()){
           documento.setActivoDocumento(1);
          }else{
               documento.setActivoDocumento(0);
          }
         
          valida=documento.actualizarDocumentos(1);
          
           if(valida){
             jTable1.setValueAt(documento.getNombreTipoDocumento(), row, 1);
             jLabel2.setVisible(true);
             jLabel2.setText("Id. Documento :  " + documento.getIdtiposDocumentos());  
          }
    } catch (Exception ex) {
        Logger.getLogger(FCrearDocumentos.class.getName()).log(Level.SEVERE, null, ex);
    }return valida;
}

private boolean habilitar(boolean valor){
     boolean valida=false;
    
    return valida; 
}
}
